# Generated by Django 5.2.7 on 2025-10-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_otpcode'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['profile'], name='api_assignm_profile_eb16ad_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['deadline'], name='api_assignm_deadlin_9bd2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['created_at'], name='api_assignm_created_4d6f00_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['profile', 'deadline'], name='api_assignm_profile_4d4ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['profile'], name='api_call_profile_bcf2ee_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['status'], name='api_call_status_2cbb12_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['call_timestamp'], name='api_call_call_ti_a8d051_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['caller'], name='api_call_caller__bf38a6_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['profile', 'status'], name='api_call_profile_acee7e_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['status'], name='api_profile_status_113278_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['type'], name='api_profile_type_3df58c_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['created_at'], name='api_profile_created_7369c0_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['apollonyar'], name='api_profile_apollon_d600a6_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['term'], name='api_profile_term_id_2b757c_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['status', 'type'], name='api_profile_status_e4b244_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['target_user'], name='api_transac_target__9e490d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['verification_status'], name='api_transac_verific_8a6f41_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['timestamp'], name='api_transac_timesta_6855dc_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type'], name='api_transac_type_7e7682_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['target_user', 'verification_status'], name='api_transac_target__c6261e_idx'),
        ),
    ]
