# Generated by Django 5.2.7 on 2025-10-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assignment_api_assignm_profile_eb16ad_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assignment',
            name='api_assignm_profile_eb16ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignment',
            name='api_assignm_deadlin_9bd2ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignment',
            name='api_assignm_created_4d6f00_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignment',
            name='api_assignm_profile_4d4ac9_idx',
        ),
        migrations.RemoveIndex(
            model_name='call',
            name='api_call_profile_bcf2ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='call',
            name='api_call_status_2cbb12_idx',
        ),
        migrations.RemoveIndex(
            model_name='call',
            name='api_call_call_ti_a8d051_idx',
        ),
        migrations.RemoveIndex(
            model_name='call',
            name='api_call_caller__bf38a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='call',
            name='api_call_profile_acee7e_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='api_profile_status_113278_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='api_profile_type_3df58c_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='api_profile_created_7369c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='api_profile_apollon_d600a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='api_profile_term_id_2b757c_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='api_profile_status_e4b244_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='api_transac_target__9e490d_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='api_transac_verific_8a6f41_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='api_transac_timesta_6855dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='api_transac_type_7e7682_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='api_transac_target__c6261e_idx',
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('active', 'آزاد'), ('suspended', 'مسدود'), ('optout', 'انصراف')], default='active', max_length=20, verbose_name='وضعیت'),
        ),
    ]
