# Generated by Django 5.2.7 on 2025-10-18 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_update_status_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان فایل')),
                ('file', models.FileField(upload_to='assignment_files/', verbose_name='فایل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت کل دوره'),
        ),
        migrations.AddField(
            model_name='log',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course', verbose_name='دوره'),
        ),
        migrations.AddField(
            model_name='note',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course', verbose_name='دوره'),
        ),
        migrations.AddField(
            model_name='assignmentdef',
            name='assignment_files',
            field=models.ManyToManyField(blank=True, related_name='assignment_defs', to='api.assignmentfile', verbose_name='فایل\u200cهای تکلیف'),
        ),
    ]
