# Generated by Django 5.2.7 on 2025-10-18 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_assignmentfile_course_total_price_log_course_and_more'),
    ]

    operations = [
        # حذف فیلد price از Term
        migrations.RemoveField(
            model_name='term',
            name='price',
        ),
        # افزودن unique constraint برای Term
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('course', 'name')},
        ),
        # افزودن فیلد course به Group
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.course', verbose_name='دوره'),
        ),
        # حذف فیلدهای قدیمی از DiscountCode
        migrations.RemoveField(
            model_name='discountcode',
            name='cash_price',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='installment_price',
        ),
        # افزودن فیلدهای جدید به DiscountCode
        migrations.AddField(
            model_name='discountcode',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='api.course', verbose_name='دوره'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='final_cash_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت نهایی نقدی با تخفیف'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='final_installment_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت نهایی قسطی با تخفیف'),
        ),
    ]
