# Generated by Django 5.2.7 on 2025-10-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20251018_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medaldef',
            name='icon',
            field=models.CharField(default='fa-solid fa-award', max_length=100, verbose_name='آیکون FontAwesome'),
        ),
    ]
